### PR TITLE
Less anvil plz

### PR DESCRIPTION
**Pull request by KA101**
Some equally-quick & brute-force-fixes to the quick-fix mod for child damage.  Feral children were a rare but remarkably dangerous hostile in the wolf dens (so making them invulnerable makes the villain unconquerable, possible run-ender if they can't be kited and contained) and spiderfood children are blind, immobile, and ask anyone (friendly) chatting to them to put them out of their misery.  PLEASE.  (Even hostiles get demanded to end the torture.)

So it's better to remove them outright than to simply make them Untouchable.  Hopefully this does so; if it doesn't work, let me know and I'll see about fixing it.

### CODE REVIEW

**Comment by SoftMonster** [comment]
This looks like it should work, but something is conflicting in the merge.

Note that the mod compatibility and future proofing is poor.

Next comment will discuss

**Comment by SoftMonster** [comment]
When modding changes to vanilla code, only change the properties you need to.

Example (forgive typos):

"MAIN_DUNGEON" modify
{
  Settlement={.............}
}

Where the .... is replaced by that code.

1) Future proofing:
If Michal changes the biome, config or level connections, you won't be left out of date.

2) Mod compatibility:
Mods that change main dungeon biome, config or level connections will still be compatible

**Comment by SoftMonster** [comment]
Note that my modifications in creatures.txt also have bad mod compatibility where feral children from other mods become immortal.

However, notice how they leave the children code alone except to change only their list of permanent effects. This is better future proofing and mod compatibility than simply overwriting all vanilla child code. It is also quicker to type in and can be cut and pasted for each type of child.

Overall you get 90% score because it fixed the bugs I made and generally looks like it should work.

Forget the merge conflicts. Take the latest code and reapply your fix and pull your changes in (test them again first).

Hint: I use the immortal keeper mod for testing, since dying on a test run won't complete the run.

Thanks for your help.

Good luck.

**Comment by SoftMonster** [comment]
Sorry the pull request wasn't noticed until today.

**Comment by KA101** [comment]
And I just saw the replies today.  My apologies.

Truth be told, I wasn't terribly concerned about mod compatibility, but since patching the children out altogether would run a higher breakage risk, I'll leave this one alone.  Thanks for taking the time to talk it out, in any event.

**Pull request closed without merging**
